apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: helloworld
spec:
  ports:
  - port: 8989
    targetPort: 8989
    nodePort: 30542
  selector:
    app: hello-server
  type: LoadBalancer